name = "aoc_day01"
version = "0.1.0"
description = "Advent of Code 2015 Puzzle for Day 01 Part 1 and Part 2"
license = "MIT"
author = "Simon Rowe"
maintainer = "simon@wiremoons.com"
copyright = "Copyright 2022, Simon Rowe"

[[ executable ]]
name = "aoc_day01_p1"
source-dir = "app"
main = "aoc_day01_p1.f90"

[[ executable ]]
name = "aoc_day01_p2"
source-dir = "app"
main = "aoc_day01_p2.f90"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
#stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }